In [2]:
import numpy as np
import pandas as pd

In [4]:
countries = ['India', 'Pakistan', 'Canada', 'Australia', 'Russia']
print(countries)
print(type(countries))
sr = pd.Series(countries)
print(sr)
print(type(sr))

['India', 'Pakistan', 'Canada', 'Australia', 'Russia']
<class 'list'>
0        India
1     Pakistan
2       Canada
3    Australia
4       Russia
dtype: object
<class 'pandas.core.series.Series'>

In [6]:
# integer index

nums = [1, 2, 3, 4, 5]

nums_series = pd.Series(nums)
print(nums_series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [9]:
marks = [90, 80, 70, 60, 50]
subjects = ['Maths', 'Science', 'English', 'History', 'Geography']

marks_series = pd.Series(marks, index=subjects)
print(marks_series)
print(type(marks_series))

Maths        90
Science      80
English      70
History      60
Geography    50
dtype: int64
<class 'pandas.core.series.Series'>

In [14]:
marks = [83, 78, 65, 90, 88]
subjects = ['Maths', 'Science', 'English', 'History', 'Geography']

data = pd.Series(marks, index=subjects, name='MCA DS & AI')
data

Maths        83
Science      78
English      65
History      90
Geography    88
Name: MCA DS & AI, dtype: int64

In [15]:
marks = {
    'Maths': 83,
    'Science': 78,
    'English': 65,
    'History': 90,
    'Geography': 88
}

marks_series = pd.Series(marks)
print(marks_series)

Maths        83
Science      78
English      65
History      90
Geography    88
dtype: int64

In [37]:
subs = pd.read_csv('subs.xls',usecols=[0]).squeeze()
print(subs)

0       48
1       57
2       40
3       43
4       44
5       46
6       33
7       40
8       44
9       74
10      49
11      56
12      49
13      42
14      39
15      44
16      54
17      51
18      40
19      37
20      40
21      45
22      50
23      56
24      35
25      49
26      46
27      88
28      61
29      42
30      56
31      50
32      50
33      49
34      76
35     123
36     108
37     110
38      56
39      62
40      65
41      66
42      33
43      66
44      82
45     126
46     109
47      88
48      83
49     108
50     101
51     128
52     111
53      96
54     101
55      99
56     105
57      72
58      93
59      76
60     104
61      70
62      80
63      99
64     104
65     136
66     115
67     123
68     112
69     145
70      87
71      84
72      92
73      80
74      70
75      70
76     132
77     123
78      98
79      96
80      88
81      86
82      92
83      92
84     110
85     120
86     105
87      72
88      84
89      90
90      78
91      81
92      89
93      89
94      93
95      86
96      95
97      83
98      72
99      87
100    100
101     72
102     79
103     67
104     71
105     90
106     77
107    100
108     88
109     65
110     95
111     78
112     89
113     96
114     81
115    105
116     80
117     66
118     73
119     68
120    159
121     90
122     83
123     76
124     77
125     66
126     64
127     85
128    136
129    135
130     71
131     79
132     75
133     72
134     78
135    109
136     93
137     84
138     74
139     87
140    128
141    105
142    105
143     82
144     86
145    100
146     88
147    104
148     87
149    119
150    118
151     97
152    114
153    117
154    102
155    101
156     96
157     90
158    114
159    118
160    113
161    123
162    129
163    140
164    180
165    225
166    249
167    265
168    306
169    261
170    222
171    170
172    160
173    114
174    175
175    170
176    115
177    152
178    105
179    105
180     93
181    110
182    102
183    136
184     76
185    105
186    130
187    146
188    146
189    105
190    146
191    150
192    114
193    113
194    117
195    108
196    103
197    108
198    138
199    124
200    139
201    117
202    103
203    108
204    146
205    131
206    113
207    108
208    125
209     91
210     97
211     98
212    119
213    115
214    123
215    119
216    127
217    135
218    137
219    156
220    160
221    122
222    111
223    131
224    192
225    224
226    254
227    214
228    236
229    261
230    247
231    207
232    254
233    301
234    233
235    168
236    179
237    154
238    152
239    153
240    202
241    185
242    158
243    173
244    180
245    184
246    259
247    196
248    213
249    210
250    179
251    182
252    216
253    183
254    185
255    159
256    180
257    160
258    154
259    147
260    138
261    157
262    134
263    184
264    134
265    132
266    119
267    153
268    185
269    138
270    150
271    134
272    160
273    170
274    175
275    228
276    237
277    276
278    173
279    290
280    295
281    245
282    241
283    267
284    269
285    211
286    186
287    206
288    202
289    176
290    236
291    222
292    203
293    190
294    190
295    170
296    156
297    172
298    174
299    157
300    178
301    189
302    174
303    157
304    173
305    162
306    151
307    115
308    152
309    150
310    186
311    156
312    230
313    186
314    150
315    153
316    167
317    183
318    244
319    158
320    155
321    167
322    157
323    196
324    243
325    227
326    259
327    183
328    166
329    154
330    396
331    312
332    268
333    229
334    197
335    188
336    176
337    221
338    225
339    221
340    202
341    171
342    185
343    184
344    276
345    258
346    219
347    212
348    192
349    164
350    192
351    220
352    196
353    197
354    204
355    149
356    156
357    177
358    210
359    209
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, dtype: int64

In [61]:
# show entire data
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [53]:
vk = pd.read_csv('kohli_ipl.xls')
print(vk)

     match_no  runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]

In [12]:
vk.shape

(215, 2)

In [54]:
movies = pd.read_csv('bollywood.xls',index_col='movie')
print(movies)

                                                  lead
movie
Uri: The Surgical Strike                 Vicky Kaushal
Battalion 609                              Vicky Ahuja
The Accidental Prime Minister (film)       Anupam Kher
Why Cheat India                          Emraan Hashmi
Evening Shadows                       Mona Ambegaonkar
...                                                ...
Hum Tumhare Hain Sanam                  Shah Rukh Khan
Aankhen (2002 film)                   Amitabh Bachchan
Saathiya (film)                           Vivek Oberoi
Company (film)                              Ajay Devgn
Awara Paagal Deewana                      Akshay Kumar

[1500 rows x 1 columns]

In [34]:
movies[movies['lead'] == 'Vicky Kaushal']

                                   lead
movie
Uri: The Surgical Strike  Vicky Kaushal
Love per Square Foot      Vicky Kaushal

In [36]:
movies[movies['lead'] == 'Vicky Kaushal'].value_counts()

lead
Vicky Kaushal    2
Name: count, dtype: int64

In [55]:
vk.sort_index()

     match_no  runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]

In [56]:
vk.sort_values(by='runs',ascending=False)

     match_no  runs
127       128   113
125       126   109
122       123   108
163       164   100
119       120   100
..        ...   ...
92         93     0
210       211     0
129       130     0
7           8     0
134       135     0

[215 rows x 2 columns]

In [40]:
# add all runs
vk['runs'].sum()

6634

In [57]:
vk.head()

   match_no  runs
0         1     1
1         2    23
2         3    13
3         4    12
4         5     1

In [58]:
print(vk.mean())
print(vk.median())
print(vk.std())
print(vk.describe())

match_no    108.000000
runs         30.855814
dtype: float64
match_no    108.0
runs         24.0
dtype: float64
match_no    62.209324
runs        26.229801
dtype: float64
         match_no        runs
count  215.000000  215.000000
mean   108.000000   30.855814
std     62.209324   26.229801
min      1.000000    0.000000
25%     54.500000    9.000000
50%    108.000000   24.000000
75%    161.500000   48.000000
max    215.000000  113.000000

In [44]:
subs.max()

396

In [45]:
vk.describe()

         match_no        runs
count  215.000000  215.000000
mean   108.000000   30.855814
std     62.209324   26.229801
min      1.000000    0.000000
25%     54.500000    9.000000
50%    108.000000   24.000000
75%    161.500000   48.000000
max    215.000000  113.000000

In [46]:
vk.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   match_no  215 non-null    int64
 1   runs      215 non-null    int64
dtypes: int64(2)
memory usage: 3.5 KB

In [47]:
subs.info()

<class 'pandas.core.series.Series'>
RangeIndex: 365 entries, 0 to 364
Series name: Subscribers gained
Non-Null Count  Dtype
--------------  -----
365 non-null    int64
dtypes: int64(1)
memory usage: 3.0 KB

In [48]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1500 entries, Uri: The Surgical Strike to Awara Paagal Deewana
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   lead    1500 non-null   object
dtypes: object(1)
memory usage: 55.7+ KB

In [59]:
movies

                                                  lead
movie
Uri: The Surgical Strike                 Vicky Kaushal
Battalion 609                              Vicky Ahuja
The Accidental Prime Minister (film)       Anupam Kher
Why Cheat India                          Emraan Hashmi
Evening Shadows                       Mona Ambegaonkar
...                                                ...
Hum Tumhare Hain Sanam                  Shah Rukh Khan
Aankhen (2002 film)                   Amitabh Bachchan
Saathiya (film)                           Vivek Oberoi
Company (film)                              Ajay Devgn
Awara Paagal Deewana                      Akshay Kumar

[1500 rows x 1 columns]

In [60]:
movies.isnull()

                                       lead
movie
Uri: The Surgical Strike              False
Battalion 609                         False
The Accidental Prime Minister (film)  False
Why Cheat India                       False
Evening Shadows                       False
...                                     ...
Hum Tumhare Hain Sanam                False
Aankhen (2002 film)                   False
Saathiya (film)                       False
Company (film)                        False
Awara Paagal Deewana                  False

[1500 rows x 1 columns]

In [63]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)